spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://maum-db.ci57v9qxvd9j.ap-northeast-2.rds.amazonaws.com:3306/maum_music?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&useSSL=false

    hikari:
      username: admin
      password: maum1230
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
server:
  port: 8093

url:
  auth:
    base: http://13.124.111.82/auth/api/v1/user
  diary:
    base: http://13.124.111.82/diary/api/v1/diary
  django:
    base: http://13.124.111.82/emotion